"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, BriefcaseBusiness, Code2, GitBranch, GraduationCap, HeartPulse, Link, Mail, MapPin, Menu, Sparkles, Trophy, X } from "lucide-react";
import { certifications, projects, skills, type Project } from "@/data/portfolio";

const navItems = ["Home","About","Projects","Experience","Education","Skills","Contact"];
const filters = ["All","Web","Mobile","AI / ML","Automation","Other"];

function SectionTitle({ eyebrow, title, subtitle }: { eyebrow:string; title:React.ReactNode; subtitle?:string }) { return <header className="section-title reveal"><span>{eyebrow}</span><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</header>; }
function ProjectVisual({ project, large=false }: { project:Project; large?:boolean }) { return <div className={`project-visual ${large?"large":""}`} style={{"--project-accent":project.accent} as React.CSSProperties}><span>{project.name.slice(0,2).toUpperCase()}</span><div><small>{project.category}</small><strong>{project.name}</strong></div></div>; }
function ProjectDetail({ project, onClose }: { project:Project; onClose:()=>void }) {
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  return <div className="detail-shell" role="dialog" aria-modal="true" aria-label={`${project.name} project details`}><div className="detail-page"><button className="back-button" onClick={onClose}><ArrowLeft size={17}/> Back to projects</button><div className="detail-head"><div><span className="eyebrow">Case study · {project.category}</span><h2>{project.name}</h2><p>{project.description}</p></div><button className="icon-button detail-close" onClick={onClose} aria-label="Close project" aria-keyshortcuts="Escape" autoFocus><X size={24}/></button></div><div className="tag-row">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><ProjectVisual project={project} large/><div className="case-grid"><article><span>01</span><h3>Overview</h3><p>{project.overview}</p></article><article><span>02</span><h3>Key features</h3><ul>{project.features.map(item=><li key={item}>{item}</li>)}</ul></article><article><span>03</span><h3>The challenge</h3><p>{project.challenge}</p></article><article><span>04</span><h3>What I learned</h3><p>{project.learned}</p></article></div></div></div>;
}

export default function Portfolio() {
  const [menuOpen,setMenuOpen]=useState(false); const [filter,setFilter]=useState("All"); const [activeProject,setActiveProject]=useState<Project|null>(null);
  const visibleProjects=useMemo(()=>filter==="All"?projects:projects.filter(project=>project.category===filter),[filter]);
  return <><nav className="navbar"><a className="brand" href="#home">SN<span>.</span></a><div className={`nav-links ${menuOpen?"open":""}`}>{navItems.map(item=><a key={item} href={`#${item.toLowerCase()}`} onClick={()=>setMenuOpen(false)}>{item}</a>)}</div><a className="nav-cta" href="#contact">Let&apos;s talk <ArrowUpRight size={15}/></a><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button></nav>
  <main>
    <section id="home" className="hero page-width"><div className="hero-copy reveal"><span className="eyebrow">Hey, I&apos;m</span><h1>Surya<br/>Nandan<span>.</span></h1><h3>Software Engineer<br/>& Frontend Developer</h3><p>I build web and mobile applications with a focus on clean design, real-world impact, and good user experiences.</p><div className="hero-actions"><a className="button primary" href="#projects">View my work <ArrowRight size={17}/></a><a className="button secondary" href="/Surya-Nandan-Resume.pdf" download>Download resume</a></div><div className="availability"><span><i/> Open to opportunities (2027)</span><span><MapPin size={15}/> Hyderabad, India</span></div></div><div className="portrait-wrap reveal"><div className="portrait-bg"/><div className="portrait-frame"><Image src="/surya-nandan.jpg" alt="Surya Nandan" fill priority sizes="(max-width: 760px) 90vw, 42vw"/></div><div className="scribble">Build.<br/>Ideas.<br/>Iterate.<br/>Repeat. <span>↙</span></div></div></section>
    <section className="selected page-width reveal"><div className="section-kicker"><span>Selected projects</span><a href="#projects">View all <ArrowRight size={15}/></a></div><div className="selected-grid">{projects.slice(0,4).map(project=><button key={project.id} onClick={()=>setActiveProject(project)}><ProjectVisual project={project}/><strong>{project.name}</strong><span>{project.category}</span></button>)}</div></section>
    <section id="about" className="section page-width about"><SectionTitle eyebrow="01 · About" title={<>About<br/>me</>}/><div className="about-copy reveal"><p className="lead">I&apos;m a final-year B.Tech student and Frontend Developer who enjoys building real-world products across web, mobile and AI.</p><p>I&apos;m currently helping shape VORQARD&apos;s doctor and patient experiences at Abhivorn Technologies. I care about the details that make software feel simpler, faster and more human.</p><div className="stats"><div><strong>3+</strong><span>Years learning</span></div><div><strong>10+</strong><span>Projects built</span></div><div><strong>2027</strong><span>Graduating</span></div></div></div><div className="what-i-do reveal"><h3>What I do</h3><div className="service-grid"><div><Code2/><strong>Frontend Development</strong><span>React, TypeScript, Tailwind</span></div><div><Sparkles/><strong>Full Stack Development</strong><span>Node.js, Databases, APIs</span></div><div><HeartPulse/><strong>Mobile Development</strong><span>React Native, Expo</span></div><div><BriefcaseBusiness/><strong>AI / Automation</strong><span>AI integrations, n8n, ML</span></div></div><div className="approach"><strong>My approach</strong><p>I solve real problems, learn continuously and improve useful products through thoughtful iteration.</p><em>Build. Learn. Share. Repeat.</em></div></div></section>
    <section id="projects" className="section page-width projects-section"><SectionTitle eyebrow="02 · Work" title="Projects" subtitle="A collection of projects I've built. Each one taught me something new."/><div className="filters" role="group" aria-label="Filter projects">{filters.map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="project-list">{visibleProjects.map((project,index)=><button className="project-row reveal" key={project.id} onClick={()=>setActiveProject(project)}><span className="project-number">{String(index+1).padStart(2,"0")}</span><ProjectVisual project={project}/><span className="project-info"><strong>{project.name}</strong><small>{project.description}</small><span className="tag-row">{project.tags.map(tag=><i key={tag}>{tag}</i>)}</span></span><ArrowUpRight className="row-arrow"/></button>)}</div></section>
    <section id="experience" className="section page-width split-section"><SectionTitle eyebrow="03 · Journey" title="Experience" subtitle="Professional experience, teaching and independent work."/><div className="timeline reveal"><article><span className="time">2026 — Present</span><i/><div><div className="role-line"><h3>UI Frontend Developer</h3><b>Current</b></div><strong>Abhivorn Technologies · VORQARD</strong><ul><li>Building Doctor and Patient interfaces across web and mobile.</li><li>Creating healthcare flows for discovery, bookings, profiles and records.</li><li>Collaborating with backend and product teams to improve UX.</li></ul></div></article><article><span className="time">Teaching Intern</span><i/><div><h3>Programming & Robotics</h3><strong>Rainbow Primary School</strong><p>Introduced young learners to block-based programming, robotics and computational thinking through practical sessions.</p></div></article><article><span className="time">2023 — Now</span><i/><div><h3>Independent Projects</h3><strong>Product design, full stack and AI</strong><p>Built streaming, fitness, travel, construction, 3D customization and local-AI developer products.</p></div></article></div></section>
    <section id="education" className="section page-width education"><SectionTitle eyebrow="04 · Education" title="Learning by building"/><div className="education-card reveal"><GraduationCap/><div><span>B.Tech in Computer Science & Engineering</span><h3>MLR Institute of Technology</h3><p>2023 — 2027 (Expected) · Hyderabad, India</p></div></div><div className="coursework reveal"><h3>Relevant coursework</h3><div>{["Data Structures & Algorithms","Database Management Systems","Operating Systems","Computer Networks","AI & Machine Learning","Web Technologies","Software Engineering","Object-Oriented Programming"].map(course=><span key={course}>{course}</span>)}</div></div><blockquote className="reveal">“I don&apos;t just study to pass exams.<br/>I study to build better things.” <BookOpen/></blockquote></section>
    <section id="skills" className="section page-width skills-section"><SectionTitle eyebrow="05 · Toolkit" title="Skills" subtitle="Tools and technologies I work with."/><div className="skills-list reveal">{Object.entries(skills).map(([group,items])=><div key={group}><h3>{group}</h3><div>{items.map(item=><span key={item}>{item}</span>)}</div></div>)}</div></section>
    <section className="section page-width more-section"><SectionTitle eyebrow="06 · More" title={<>Achievements<br/>& more</>}/><div className="more-list reveal"><article><Trophy/><div><h3>Operation CodeX</h3><p>Recognized for exceptional performance in a coding contest conducted by SQUAD Club at MLRIT.</p></div><span>2025</span></article><article><GitBranch/><div><h3>Open source & GitHub</h3><p>Projects, experiments and the systems I&apos;m actively learning through.</p></div><a href="https://github.com/SuryaNandan07" target="_blank">Visit GitHub <ArrowUpRight size={16}/></a></article><article><BookOpen/><div><h3>Certifications</h3>{certifications.map(item=><p key={item}>{item}</p>)}</div></article></div></section>
    <section id="contact" className="contact-section"><div className="page-width contact-grid"><div><span className="eyebrow">07 · Contact</span><h2>Let&apos;s<br/>talk<span>.</span></h2><p>Feel free to reach out. I&apos;m open to opportunities, collaborations and interesting projects.</p><a className="button primary" href="mailto:gvsnandan07@gmail.com">Send a message <ArrowUpRight size={17}/></a></div><div className="contact-links"><a href="mailto:gvsnandan07@gmail.com"><Mail/><span>Email<small>gvsnandan07@gmail.com</small></span><ArrowUpRight/></a><a href="https://linkedin.com/in/venkata-surya-nandan-g" target="_blank"><Link/><span>LinkedIn<small>venkata-surya-nandan-g</small></span><ArrowUpRight/></a><a href="https://github.com/SuryaNandan07" target="_blank"><GitBranch/><span>GitHub<small>SuryaNandan07</small></span><ArrowUpRight/></a><div><MapPin/><span>Location<small>Hyderabad, India</small></span></div><em>Have an idea?<br/>A project?<br/>Or just want to say hi?<br/>I&apos;d love to connect! ↙</em></div></div><footer className="page-width"><span>© 2026 Surya Nandan</span><span>Thanks for visiting! :)</span><a href="#home">Back to top ↑</a></footer></section>
  </main>{activeProject&&<ProjectDetail project={activeProject} onClose={()=>setActiveProject(null)}/>}</>;
}
